[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "finclients"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []  # add 'httpx' or vendor SDKs here if you use them

[tool.hatch.build.targets.wheel]
packages = ["src/finclients"]