[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "common"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pydantic>=2.7"]

[tool.hatch.build.targets.wheel]
packages = ["src/common"]
